### ISSUE TITLE
Improve CI settings

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#30]
As discussed in #28, here are 2 steps to improve our travis build process.
Of course don't add my config comments, that's just for clarification ;)
# Cache and containerized CI

Add those lines to your `.travis.yml` :

``` yml
sudo: false # Enables containerized CI

# The following is all to deal with cache
cache:
  directories: # Which directories to keep between builds
    - node_modules
install: npm update # Since the modules are cached, we have to update on every build
```
# NPM release

If you also want to publish new versions to npm after a successful build on a tag, first [install the travis CLI](https://github.com/travis-ci/travis.rb#installation).
Then do a `travis setup npm` and answer the few questions (you have to fill information of someone with publish authorization on npm).
Once done, you'll have a basic npm deploy section which should be completed accordingly :

``` yaml
deploy:
  provider: npm
  email: <some email>
  api_key:
    secure: <encrypted api key>
  on:
    branch: master # Only deploy on master
    tags: true # Only deploy on tags
    repo: hapijs/joi # Probably auto-filled, can't remember
    node: "0.10" # Only deploy one of the version, pick one, otherwise travis will try to publish on all CI versions (and probably fail)
```
